name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Jekyll
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2

    - name: Build site
      run: bundle exec jekyll build

    - name: Configure Git author
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        publish_dir: ./_site
